"""MCP 全局配置常量"""

PYTHON_WORKSPACE_BASE = "/tmp/ontology_python_workspace"
PYTHON_WORKSPACE_TTL_SEC = 3600
PYTHON_RUNTIME_TIMEOUT_SEC = 60
PYTHON_RUNTIME_MAX_TIMEOUT_SEC = 300

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 5000
MAX_RETURN_ROWS = 5000

MCP_SERVER_NAME = "元枢 Ontology MCP Server"
MCP_SERVER_VERSION = "1.0.0"
